// GET /api/integrations/gmail/callback — OAuth callback
import { NextRequest, NextResponse } from 'next/server'
import { getSession } from '@/lib/auth'
import { handleGmailCallback, verifyOAuthState } from '@/lib/gmail-oauth'
import { recordCampaignEvent } from '@/lib/queries/campaign-queries'

export async function GET(req: NextRequest): Promise<NextResponse> {
  const { searchParams } = req.nextUrl
  const code = searchParams.get('code')
  const state = searchParams.get('state')
  const error = searchParams.get('error')

  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000'

  if (error || !code) {
    // Google returned an error param or omitted the code — log it so the
    // user can surface it to support if the redirect querystring doesn't
    // carry enough detail.
    console.error('[gmail/callback] google returned error:', { error, hasCode: Boolean(code) })
    await recordCampaignEvent({
      eventType: 'gmail_callback_error',
      severity: 'error',
      message: error ?? 'no_code',
      metadata: { phase: 'pre_session' },
    })
    return NextResponse.redirect(`${appUrl}/dashboard?gmail_error=${error ?? 'no_code'}`)
  }

  try {
    const session = await getSession()
    if (!session) {
      return NextResponse.redirect(`${appUrl}/signin`)
    }

    // Reject callbacks whose state wasn't generated by this user's session.
    if (!state || !verifyOAuthState(state, session.userId)) {
      console.error('[gmail/callback] invalid state for user', session.userId)
      await recordCampaignEvent({
        userId: session.userId,
        eventType: 'gmail_callback_error',
        severity: 'error',
        message: 'invalid_state',
      })
      return NextResponse.redirect(`${appUrl}/dashboard?gmail_error=invalid_state`)
    }

    const result = await handleGmailCallback(session.userId, code)
    await recordCampaignEvent({
      userId: session.userId,
      eventType: 'gmail_connected',
      metadata: { email: result.emailAddress },
    })
    return NextResponse.redirect(
      `${appUrl}/dashboard?gmail_connected=1&email=${encodeURIComponent(result.emailAddress)}`
    )
  } catch (err) {
    console.error('[gmail/callback] error:', err)
    const msg = err instanceof Error ? err.message : 'unknown'
    await recordCampaignEvent({
      eventType: 'gmail_callback_error',
      severity: 'error',
      message: msg,
    })
    return NextResponse.redirect(`${appUrl}/dashboard?gmail_error=${encodeURIComponent(msg)}`)
  }
}
