// GET /api/integrations/gmail/callback — OAuth callback
import { NextRequest, NextResponse } from 'next/server'
import { getSession } from '@/lib/auth'
import { handleGmailCallback, verifyOAuthState, getReturnToFromState } from '@/lib/gmail-oauth'
import { recordCampaignEvent } from '@/lib/queries/campaign-queries'
import { logError } from '@/lib/log'

export async function GET(req: NextRequest): Promise<NextResponse> {
  const { searchParams } = req.nextUrl
  const code = searchParams.get('code')
  const state = searchParams.get('state')
  const error = searchParams.get('error')

  // Trim stray whitespace/trailing slash so post-auth redirects are well-formed
  // even if NEXT_PUBLIC_APP_URL was set with an accidental trailing space.
  const appUrl = (process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000').trim().replace(/\/+$/, '')

  if (error || !code) {
    // Google returned an error param or omitted the code — log it so the
    // user can surface it to support if the redirect querystring doesn't
    // carry enough detail.
    console.error('[gmail/callback] google returned error:', { error, hasCode: Boolean(code) })
    await recordCampaignEvent({
      eventType: 'gmail_callback_error',
      severity: 'error',
      message: error ?? 'no_code',
      metadata: { phase: 'pre_session' },
    })
    return NextResponse.redirect(`${appUrl}/dashboard?gmail_error=${error ?? 'no_code'}`)
  }

  try {
    const session = await getSession()
    if (!session) {
      return NextResponse.redirect(`${appUrl}/signin`)
    }

    // Reject callbacks whose state wasn't generated by this user's session.
    if (!state || !verifyOAuthState(state, session.userId)) {
      console.error('[gmail/callback] invalid state for user', session.userId)
      await recordCampaignEvent({
        userId: session.userId,
        eventType: 'gmail_callback_error',
        severity: 'error',
        message: 'invalid_state',
      })
      return NextResponse.redirect(`${appUrl}/dashboard?gmail_error=invalid_state`)
    }

    const result = await handleGmailCallback(session.userId, code)
    await recordCampaignEvent({
      userId: session.userId,
      eventType: 'gmail_connected',
      metadata: { email: result.emailAddress },
    })
    // Return the user to the page they started from (sanitized same-origin path),
    // falling back to the dashboard home.
    const returnTo = getReturnToFromState(state) ?? '/dashboard'
    const sep = returnTo.includes('?') ? '&' : '?'
    return NextResponse.redirect(
      `${appUrl}${returnTo}${sep}gmail_connected=1&email=${encodeURIComponent(result.emailAddress)}`
    )
  } catch (err) {
    logError('integrations/gmail/callback', err, { msg: '[gmail/callback] error' })
    const msg = err instanceof Error ? err.message : 'unknown'
    await recordCampaignEvent({
      eventType: 'gmail_callback_error',
      severity: 'error',
      message: msg,
    })
    // Don't bounce raw exception text into the user's URL bar — it can leak
    // Google client_id, internal stack details, etc. The full error is in the
    // server log and campaign_events; show the user a stable code only.
    return NextResponse.redirect(`${appUrl}/dashboard?gmail_error=callback_failed`)
  }
}
