import type { BillingModuleId } from '@/lib/billing'

export type ScopeGuardModuleId = BillingModuleId

export interface ModuleScopeDefinition {
  id: ScopeGuardModuleId
  summary: string
  contextKey: string | null
  primaryDeliverables: string[]
  keywords: string[]
  editKeywords: string[]
  redirectPriority: BillingModuleId[]
}

export interface ScopeRefusalResult {
  kind: 'scope_refusal'
  moduleId: ScopeGuardModuleId
  blockedBy: 'deterministic' | 'classifier'
  confidence: number
  reason: string
  message: string
  suggestedModules: BillingModuleId[]
}

export const MODULE_SCOPE_REGISTRY: Record<ScopeGuardModuleId, ModuleScopeDefinition> = {
  research: {
    id: 'research',
    summary: 'market research, competitor analysis, TAM/SAM/SOM sizing, and venture validation',
    contextKey: 'research',
    primaryDeliverables: [
      'market research',
      'competitor analysis',
      'tam',
      'sam',
      'som',
      'market sizing',
      'pain points',
      'swot',
      'risk matrix',
      'business concepts',
      'opportunity paper',
    ],
    keywords: [
      'market',
      'competitor',
      'validation',
      'audience research',
      'market gap',
      'feasibility overview',
      'trends',
      'research',
    ],
    editKeywords: [
      'tam',
      'sam',
      'som',
      'pain points',
      'competitors',
      'swot',
      'risk matrix',
      'concept',
      'research paper',
      'market summary',
    ],
    redirectPriority: ['landing', 'marketing', 'feasibility', 'branding'],
  },
  branding: {
    id: 'branding',
    summary: 'brand identity, naming, voice, color palette, typography, and design direction',
    contextKey: 'branding',
    primaryDeliverables: [
      'brand name',
      'tagline',
      'brand bible',
      'color palette',
      'typography',
      'logo',
      'brand voice',
      'tone of voice',
      'brand archetype',
      'ui kit',
    ],
    keywords: [
      'branding',
      'identity',
      'voice',
      'tone',
      'palette',
      'logo concept',
      'mission statement',
      'archetype',
    ],
    editKeywords: [
      'brand name',
      'tagline',
      'mission',
      'archetype',
      'voice',
      'color',
      'palette',
      'typography',
      'logo',
      'ui kit',
    ],
    redirectPriority: ['landing', 'marketing', 'research', 'feasibility'],
  },
  marketing: {
    id: 'marketing',
    summary: 'go-to-market strategy, social content, SEO outlines, and launch messaging',
    contextKey: 'marketing',
    primaryDeliverables: [
      'marketing plan',
      'go to market',
      'gtm',
      'social calendar',
      'social media calendar',
      'captions',
      'hashtags',
      'email sequence',
      'launch emails',
      'seo outlines',
      'blog outlines',
      'campaign',
    ],
    keywords: [
      'marketing',
      'distribution',
      'content calendar',
      'launch strategy',
      'channel strategy',
      'social posts',
      'seo',
      'email copy',
    ],
    editKeywords: [
      'gtm',
      'social calendar',
      'caption',
      'hashtags',
      'email',
      'seo',
      'blog outline',
      'marketing plan',
    ],
    redirectPriority: ['launch-autopilot', 'landing', 'branding', 'research'],
  },
  landing: {
    id: 'landing',
    summary: 'landing page strategy, page copy, sitemap, UI structure, and live page components',
    contextKey: 'landing',
    primaryDeliverables: [
      'landing page',
      'hero section',
      'cta',
      'headline',
      'subheadline',
      'sitemap',
      'pricing section',
      'faq section',
      'landing page copy',
      'website',
      'wireframe',
      'component',
      'page design',
    ],
    keywords: [
      'landing',
      'page',
      'copy',
      'design',
      'site map',
      'hero',
      'pricing table',
      'web page',
    ],
    editKeywords: [
      'hero',
      'headline',
      'subheadline',
      'cta',
      'features',
      'pricing',
      'faq',
      'sitemap',
      'component',
      'seo metadata',
    ],
    redirectPriority: ['branding', 'marketing', 'research', 'launch-autopilot'],
  },
  feasibility: {
    id: 'feasibility',
    summary: 'financial modeling, risk assessment, market timing, and GO/NO-GO evaluation',
    contextKey: 'feasibility',
    primaryDeliverables: [
      'financial projections',
      'financial model',
      'feasibility study',
      'go/no-go',
      'go no go',
      'market timing',
      'break even',
      'break-even',
      'cac',
      'ltv',
      'unit economics',
      'risk assessment',
      'payback period',
    ],
    keywords: [
      'feasibility',
      'economics',
      'assumptions',
      'revenue',
      'costs',
      'profitability',
      'cash flow',
      'verdict',
    ],
    editKeywords: [
      'verdict',
      'timing',
      'revenue',
      'costs',
      'net income',
      'break even',
      'cac',
      'ltv',
      'assumptions',
      'risks',
    ],
    redirectPriority: ['research', 'investor-kit', 'shadow-board', 'mvp-scalpel'],
  },
  'full-launch': {
    id: 'full-launch',
    summary: 'an end-to-end venture package spanning research, branding, landing page work, and feasibility',
    contextKey: null,
    primaryDeliverables: [
      'full launch',
      'complete launch',
      'complete venture package',
      'end to end launch',
      'end-to-end launch',
      'run all agents',
      'everything',
      'complete package',
    ],
    keywords: [
      'launch this venture',
      'go live',
      'full package',
      'venture blueprint',
      'all agents',
      'complete business',
    ],
    editKeywords: [],
    redirectPriority: ['research', 'branding', 'landing', 'feasibility'],
  },
  general: {
    id: 'general',
    summary: 'open-ended venture advice, discussion, and module recommendations',
    contextKey: null,
    primaryDeliverables: [],
    keywords: ['advice', 'brainstorm', 'help me think', 'cofounder', 'what should i do'],
    editKeywords: [],
    redirectPriority: ['research', 'branding', 'marketing', 'landing', 'feasibility'],
  },
  'shadow-board': {
    id: 'shadow-board',
    summary: 'brutal board-style feedback, pivots, synthetic user reactions, and survival scoring',
    contextKey: 'shadowBoard',
    primaryDeliverables: [
      'shadow board',
      'board review',
      'board meeting',
      'survival score',
      'strategic pivots',
      'synthetic user interviews',
      'brutal feedback',
    ],
    keywords: [
      'skeptic',
      'evangelist',
      'alchemist',
      'stress test',
      'board feedback',
      'pivots',
    ],
    editKeywords: [
      'survival score',
      'verdict',
      'board dialogue',
      'pivot',
      'feedback',
    ],
    redirectPriority: ['feasibility', 'research', 'mvp-scalpel', 'investor-kit'],
  },
  'investor-kit': {
    id: 'investor-kit',
    summary: 'investor-facing fundraising assets like pitch decks, memos, asks, and data room structure',
    contextKey: 'investorKit',
    primaryDeliverables: [
      'pitch deck',
      'investor deck',
      'investment memo',
      'one page memo',
      'executive summary',
      'fundraising',
      'raise amount',
      'use of funds',
      'data room',
    ],
    keywords: [
      'investor',
      'fundraise',
      'raise',
      'memo',
      'deck',
      'venture capital',
      'seed round',
    ],
    editKeywords: [
      'executive summary',
      'pitch deck',
      'memo',
      'ask',
      'milestones',
      'data room',
    ],
    redirectPriority: ['feasibility', 'research', 'branding', 'landing'],
  },
  'launch-autopilot': {
    id: 'launch-autopilot',
    summary: 'a day-by-day launch calendar with paste-ready posts, outreach copy, and launch checklists',
    contextKey: 'launchAutopilot',
    primaryDeliverables: [
      'launch plan',
      'launch calendar',
      '14 day launch',
      '14-day launch',
      'product hunt',
      'cold outreach',
      'paste ready',
      'paste-ready',
      'launch checklist',
      'exact copy',
    ],
    keywords: [
      'launch execution',
      'daily launch',
      'outreach',
      'launch day',
      'comment replies',
      'micro influencers',
    ],
    editKeywords: [
      'launch plan',
      'day 1',
      'day 2',
      'task',
      'checklist',
      'channel',
      'copy',
      'week one goal',
      'week two goal',
    ],
    redirectPriority: ['marketing', 'landing', 'branding', 'research'],
  },
  'mvp-scalpel': {
    id: 'mvp-scalpel',
    summary: 'scope-cutting, skeleton MVP definition, weekend build specs, and first-dollar plans',
    contextKey: 'mvpScalpel',
    primaryDeliverables: [
      'mvp spec',
      'skeleton mvp',
      'kill list',
      'scope creep',
      'feature cut',
      'weekend build',
      'weekend plan',
      'time to first dollar',
      'ship now',
    ],
    keywords: [
      'scope',
      'mvp',
      'cut features',
      'lean build',
      'weekend ship',
      'minimal product',
      'first dollar',
    ],
    editKeywords: [
      'kill list',
      'mvp',
      'weekend spec',
      'tech stack',
      'pages',
      'endpoints',
      'first dollar',
      'verdict',
    ],
    redirectPriority: ['feasibility', 'landing', 'launch-autopilot', 'research'],
  },
}

export function isScopeRefusalResult(value: unknown): value is ScopeRefusalResult {
  if (!value || typeof value !== 'object') return false

  const candidate = value as Partial<ScopeRefusalResult>
  return (
    candidate.kind === 'scope_refusal' &&
    typeof candidate.moduleId === 'string' &&
    typeof candidate.message === 'string' &&
    typeof candidate.reason === 'string' &&
    typeof candidate.confidence === 'number' &&
    Array.isArray(candidate.suggestedModules)
  )
}
